// Все строки интерфейса в одном месте — для будущей i18n.
export const S = {
  common: {
    appName: 'ZAP!',
    uzs: 'UZS',
    cancel: 'Отмена',
    close: 'Закрыть',
    back: 'Назад',
    done: 'Готово',
    add: 'ДОБАВИТЬ',
    search: 'Найти',
    you: 'Вы',
    copy: 'Скопировать ссылку',
    copied: 'Ссылка скопирована',
    linkShared: 'Ссылка отправлена',
    shareUnavailable: 'Поделиться недоступно — ссылка скопирована',
    people: 'человек',
  },
  onboarding: {
    stage: (n: number) => `ЭТАП ${n}`,
    s1Title: 'Сканируй счёт',
    s1Text: 'QR на чеке или кассе — ZAP! сам подтянет заказ, позиции и сумму.',
    s2TitleA: 'Дели поровну,',
    s2TitleB: 'вручную или в долг',
    s2Text: 'Каждому улетает ссылка — свою долю платят сами. У кого нет денег — возьмёт у тебя в долг прямо в ZAP!',
    s2Chips: ['Поровну', 'Вручную', 'В долг'],
    s3TitleA: 'Кэшбэк ×2',
    s3TitleB: 'на всю группу',
    s3Text: 'Сплитите вместе у партнёров — каждый получает бонус, а группа копит общий кэшбэк.',
    s3Counter: 'ГРУППОВОЙ КЭШБЭК',
    tapHint: 'Коснись, чтобы дальше →',
    start: 'Начать',
    haveAccount: 'У меня уже есть аккаунт',
  },
  auth: {
    phoneTitle: 'Ваш номер',
    phoneHint: 'Пришлём код по SMS — пароль не нужен',
    terms: 'Согласен с условиями и политикой ZAP!',
    getCode: 'Получить код',
    codeTitle: 'Код из SMS',
    codeHint: 'Отправили на',
    notArrived: 'Не пришло?',
    resend: 'Отправить ещё раз',
    resendReady: 'Отправить код ещё раз',
    codeResent: 'Код отправлен ещё раз',
    pinTitle: 'Дальше придумаете PIN',
    pinSectionHint: '4 цифры для подтверждения оплат — вместо пароля',
    pinCreate: 'Придумайте PIN',
    pinRepeat: 'Повторите PIN',
    pinMismatch: 'PIN не совпадает — попробуйте ещё раз',
    pinHint: '4 цифры для подтверждения оплат',
  },
  tabs: {
    home: 'Главная',
    history: 'История',
    split: 'Сплит',
    cashback: 'Кэшбэк',
    profile: 'Профиль',
  },
  home: {
    promoTitle: 'Приди с 5 друзьями — получи кэшбэк ×2',
    promoText: 'Групповой кэшбэк начисляется каждому',
    filters: ['Все', 'Кэшбэк', 'Акции', '% Скидки'],
    searchPlaceholder: 'Имя или номер',
    split: 'Сплит',
    cashbackCard: 'Накопленные кэшбеки',
    debtorsCard: 'Мои должники',
    debtorsCount: (n: number) => `${n} общих должника`,
    myGroups: 'МОИ ГРУППЫ',
    yourSplits: 'ВАШИ СПЛИТЫ',
    closedBadge: 'ЗАКРЫТ',
    activePill: (name: string) => `Активный сплит · ждём ${name}`,
    activePillPaid: 'Активный сплит · всё оплачено',
    available: 'ДОСТУПНО',
  },
  scan: {
    hint: 'Наведите камеру на QR-код на чеке',
    detected: 'Счёт найден',
    manual: 'Ввести сумму вручную',
  },
  bill: {
    order: 'заказ',
    table: 'стол',
    total: 'ИТОГО',
    split: 'Разделить',
    payWhole: 'Оплатить целиком',
    x2Banner: 'Кэшбэк ×2 — если сплитите вдвоём и больше',
  },
  amount: {
    title: 'Сумма',
    yourAmount: 'UZS · СУММА',
    pay: 'Оплатить',
    split: 'Сплит',
  },
  members: {
    title: 'С кем делим?',
    forWhat: 'За что',
    forWhatPlaceholder: 'Ужин пятница 🍕',
    modes: { equal: 'Поровну', manual: 'Вручную', items: 'Позиции' },
    perPerson: (v: string) => `по ${v} на человека`,
    youPayNow: 'оплатите сразу',
    viaSms: 'ссылка в SMS',
    debtToggle: 'В ДОЛГ',
    debtNote: 'сейчас без денег — беру в долг',
    addContacts: 'ДОБАВИТЬ',
    byNumber: '+ Номер',
    allContacts: 'Все контакты ›',
    sumMismatch: (v: string) => `Не хватает ${v} до итога`,
    sumOver: (v: string) => `Сумма больше итога на ${v}`,
    itemsUnassigned: (n: number) => `Не распределено позиций: ${n}`,
    ctaSplit: (v: string) => `Сплит · оплатить ${v}`,
    ctaSub: (mine: string, debt?: { name: string; amount: string }) =>
      debt ? `Ваша доля ${mine} + доля ${debt.name} в долг ${debt.amount}` : `Ваша доля ${mine}`,
  },
  pin: {
    confirmTitle: 'Подтвердите PIN',
    confirmHint: 'Введите PIN для оплаты',
    wrong: 'Неверный PIN',
    demoHint: 'Демо: любой PIN из 4 цифр',
  },
  share: {
    title: 'Покажите QR друзьям',
    subtitle: 'Или отправьте ссылку — оплата в пару касаний',
    statusPaidWaiting: (names: string) => `Вы оплатили · ждём ${names}`,
    sendSms: 'Отправить SMS со ссылкой',
    toStatus: 'К статусу сплита',
  },
  live: {
    title: 'Сплит',
    paidOf: (paid: string, total: string) => `${paid} оплачено из ${total}`,
    statusPaid: 'Готово',
    statusOpened: 'открыл ссылку',
    statusWaiting: 'Ждём',
    statusDebt: 'в долг · вы покрыли',
    remind: (name: string) => `Напомнить ${name}`,
    reminded: 'Напоминание отправлено',
    coverRest: (v: string) => `Покрыть остаток — ${v}`,
    coverNote: 'Доля друга станет его долгом перед вами',
  },
  closed: {
    title: 'Готово, сплит закрыт',
    subtitle: 'Все доли собраны',
    cashbackBadge: (v: string) => `+${v} групповой кэшбэк`,
    covered: 'вы покрыли — он вам должен',
    groupTotal: (name: string, v: string) => `Всего у ${name} · ${v}`,
    saveGroup: 'Сохранить группу',
  },
  saveGroup: {
    title: 'Сохранить эту компанию?',
    subtitle: 'Сплитьте в одно касание и копите общий кэшбэк',
    namePlaceholder: 'Название группы',
    accrue: 'Копить групповой кэшбэк',
    save: 'Сохранить группу',
    notNow: 'Не сейчас',
    saved: 'Группа сохранена',
  },
  cashbackAward: {
    title: 'Кэшбэк зачислен',
    reason: (n: number) => `×2 — потому что сплитили ${n === 2 ? 'вдвоём' : n === 3 ? 'втроём' : 'вместе'}`,
    perMember: 'КАЖДОМУ УЧАСТНИКУ',
    afterDebt: 'после возврата долга',
    spend: 'Потратить кэшбэк',
    keep: 'Копить дальше',
    toast: (v: string) => `Кэшбэк зачислен +${v}`,
  },
  participant: {
    asks: (name: string) => `${name} просит вашу долю`,
    yourShare: 'UZS · ВАША ДОЛЯ',
    chipMine: 'моя доля',
    chipHalf: 'половина',
    chipTwo: 'за двоих',
    custom: '···',
    hint: 'Внесёте всей группой — кэшбэк ×2 каждому',
    pay: (v: string) => `Внести ${v}`,
    later: 'Позже · напомнить вечером',
    laterToast: 'Хорошо, напомним вечером',
    paidTitle: 'Доля внесена!',
    paidText: 'Кэшбэк ×2 придёт, когда сплит закроется',
    viewAs: 'СМОТРЕТЬ КАК',
    notFound: 'Сплит не найден или уже закрыт',
    alreadyPaid: 'Ваша доля уже внесена',
  },
  group: {
    newSplit: 'Новый сплит',
    invite: 'Позвать',
    cashback: 'КЭШБЭК ГРУППЫ',
    members: 'УЧАСТНИКИ',
    owner: 'владелец',
    owes: (v: string) => `должен вам ${v}`,
    remind: 'Напомнить',
    splits: 'СПЛИТЫ ГРУППЫ',
    sinceLabel: 'вместе с',
    merchants: (n: number) => `${n} заведения`,
  },
  debts: {
    title: 'Вам должны',
    tabOwedToMe: 'Вам должны',
    tabIOwe: 'Вы должны',
    remind: 'Напомнить',
    reminded: 'Отправлено',
    remindedToast: 'Напоминание отправлено',
    remindAll: 'Напомнить всем',
    remindAllToast: 'Напомнили всем должникам',
    autoNote: 'Долг закроется автоматически, когда друг вернёт деньги через ZAP',
    empty: 'Долгов нет — красота',
    promised: 'обещал в пн',
  },
  cashback: {
    title: 'Кэшбэк',
    available: 'ДОСТУПНО',
    filters: ['Все группы'],
    spend: 'Потратить на следующий сплит',
    withdraw: 'Вывести на карту',
    spendToast: 'Кэшбэк применим к следующему сплиту',
    withdrawToast: 'Вывод на карту ··4821 — в течение минуты',
    heldNote: 'после возврата долга',
  },
  history: {
    title: 'История',
    tabs: ['Все', 'Сплиты', 'Кэшбэк', 'Долги'],
    empty: 'Пока пусто',
  },
  profile: {
    title: 'Профиль',
    since: (d: string) => `ZAP! с ${d}`,
    stats: (splits: number, cb: string, groups: number) => ({
      splits: `${splits} сплита`,
      cashback: `${cb} кэшбэк`,
      groups: `${groups} группы`,
    }),
    cards: 'КАРТЫ',
    primary: 'основная',
    addCard: '+ Добавить карту',
    addCardTitle: 'Новая карта',
    cardNumber: 'Номер карты',
    cardAdded: 'Карта добавлена',
    settings: 'НАСТРОЙКИ',
    pinFaceId: 'PIN и Face ID',
    debtNotifs: 'Уведомления о долгах',
    myGroups: 'Мои группы',
    logout: 'Выйти',
    logoutNote: 'Демо сбросится к началу',
  },
  pwa: {
    installHint: 'Добавьте ZAP! на главный экран — работает как приложение',
  },
} as const
